### ISSUE TITLE
Strange plugin behavior

### ISSUE THREAD

**Issue by Krishnacore** [itsmereal/og-image-overlay#1]
First, I want to say thank you so much for the work done! This is the case when one small addition makes life incredibly better! But...

I found several problems here that I cannot find an explanation for.

1. Scraping of the image in the debugger occurs only once (checked not only in the FB). Further, any change to the featured image in the post does not lead to a change in the OG. And this is very strange, because the link that generates this image - everything is fine, it is updated.

2. For posts without the featured image, they do not generate OG at all in the debugger and when sharing. By direct link for generation, as in the first case, everything is ok.

**Comment by itsmereal** [comment]
Hello @Krishnacore. I have checked the plugin with the latest version of WordPress and the default Twenty Twenty theme. Everything looked OK. Please make sure the cache is cleared otherwise the change in the Featured image might not show in Facebook Debugger.
