### ISSUE TITLE
Alternative to Query Parameters for Static Websites

### ISSUE THREAD

**Issue by 972creative** [itsmereal/og-image-overlay#5]
Hi there 

Absolutely love the idea behind this plugin. 

We're stuck with a major hurdle though. We're running our WordPress website static, using [Strattic](https://www.strattic.com/), and query parameters don't play well in the static world. 

Can your code be tweaked in order to use regular URLs instead?

Would really appreciate your help.

Thanks!
Todd

**Comment by itsmereal** [comment]
With v1.4 the plugin will use image links like 

`https://{site_url}/ogio/{post_id}`

Hopefully it works for you.
