### ISSUE TITLE
Missed a lot's of explination

### ISSUE THREAD

**Issue by mxmkmarquette** [itsmereal/og-image-overlay#6]
bro you cannot simply make a plugin, a well done plugin, and left people on their own, if not yoast, or rank math, like i search google all around, stackoverflow, github, gist, and i did not find a clue of how to integrate it without those 2 software, so please give at least how to do it or just forget it, like i like innovation, but like if i had to be a programmer, level 100000 to add a plugin, what will be the purpose, i did my homework so please help and its not to be vile against you just oh you can use that or that or get lost.

**Comment by rghedin** [comment]
That's a rude comment, @mxmkmarquette :(

If you want to deploy this awesome plugin without Yoast or Rank Math, but this in your `<head>`:

```
<meta property="og:image" content="https://staging.manualdousuario.net/ogio/<?php global $post; echo $post->ID; ?>">
```

Notice that it only works properly with single posts.
